export const projects = [
  {
    id: "nocta",
    name: "Nocta Fields",
    sub: "Kinetic identity for a regenerative-energy think tank",
    client: "Halcyon Futures",
    year: "2026",
    type: "Identity",
    tone: "#c8e4ff",
  },
  {
    id: "halden",
    name: "Halden OS",
    sub: "Interface toolkit for an autonomous lab network",
    client: "Halden Institute",
    year: "2025",
    type: "Interface",
    tone: "#ffd7b0",
  },
  {
    id: "volute",
    name: "Volute",
    sub: "Generative plotter + type tester, licensed to studios",
    client: "KEFKA / licensed",
    year: "2025",
    type: "Tooling",
    tone: "#d8d0c0",
  },
  {
    id: "mirror",
    name: "Mirror Depot",
    sub: "Brand + wayfinding for an industrial reuse warehouse",
    client: "Mirror Depot",
    year: "2024",
    type: "Identity",
    tone: "#b8c8b0",
  },
  {
    id: "atlas",
    name: "Atlas / 08",
    sub: "Residency — one week, one team, one rendered artifact",
    client: "Atlas Collective",
    year: "2024",
    type: "Residency",
    tone: "#e8c0d0",
  },
  {
    id: "parabola",
    name: "Parabola",
    sub: "Spatial-audio interface for a live performance venue",
    client: "Parabola Hall",
    year: "2023",
    type: "Interface",
    tone: "#b0c4d8",
  },
];

export const journalEntries = [
  {
    idx: 47,
    date: "14·APR·2026",
    title: "On the difference between a form and a formula.",
    sub: "Generative systems aren't pattern generators; they're grammar. A field-note on where the two diverge.",
    type: "Essay",
    author: "Noa Helbig",
    read: "11 MIN",
  },
  {
    idx: 46,
    date: "29·MAR·2026",
    title: "The plotter in the corner keeps making decisions for us.",
    sub: "What a year of drawing with a pen-plotter taught us about letting materials argue back.",
    type: "Process",
    author: "Diego Lares",
    read: "7 MIN",
  },
  {
    idx: 45,
    date: "02·MAR·2026",
    title: "Dispatch from Halden, week four.",
    sub: "Residency notes: a lab, a kettle, and a spec we rewrote three times before Monday.",
    type: "Dispatch",
    author: "Studio",
    read: "4 MIN",
  },
  {
    idx: 44,
    date: "18·FEB·2026",
    title: "A type system should be quieter than the thing it labels.",
    sub: "Against display-weight maximalism in interface typography.",
    type: "Essay",
    author: "Maya Ocampo",
    read: "9 MIN",
  },
  {
    idx: 43,
    date: "30·JAN·2026",
    title: "We retired twelve colors in January.",
    sub: "Process post on pruning a palette instead of growing it.",
    type: "Process",
    author: "Studio",
    read: "6 MIN",
  },
  {
    idx: 42,
    date: "08·JAN·2026",
    title: "Dispatch: the brief we couldn't take.",
    sub: "On the engagement we declined, and why we wrote the client a book instead.",
    type: "Dispatch",
    author: "Noa Helbig",
    read: "5 MIN",
  },
];

export const contactFaq = [
  {
    n: "01",
    q: "Do you take on small projects?",
    a: "Yes, occasionally. We keep a quarterly slot for smaller engagements that are interesting on their own merits.",
  },
  {
    n: "02",
    q: "How long is a typical engagement?",
    a: "Identities run 3–8 weeks. Interface work is usually 6–14. Residencies are exactly one week. Tooling is scoped per release.",
  },
  {
    n: "03",
    q: "Will you sign an NDA?",
    a: "Yes. Send yours, or ask and we'll send our standard mutual. We also default to not publishing work until the client launches.",
  },
  {
    n: "04",
    q: "Do you work with agencies?",
    a: "Sometimes, when the handoff is clear and we'll be named in the credits. We don't white-label.",
  },
];
